### PR TITLE
provide ability to write processed resources to file

### PR DESCRIPTION
**Pull request by vinny-sabatini**

### CODE REVIEW

**Comment by sanbornick** [comment]
@jkupferer this is to enable the use of this role as a template processor image for Eunomia

**Comment by vinny-sabatini** [comment]
I will be testing the template processor in Eunomia using this branch and will comment here when I verify it all works as expected.

**Comment by seanmalloy** [comment]
This is required for KohlsTechnology/eunomia/issues/108

**Comment by vinny-sabatini** [comment]
I'm thinking this might not be necessary anymore, I'm trying a different method for implementing the template processor
Please hold off on merging this...I'm running into issues when I don't provide the new variable...

**Comment by vinny-sabatini** [comment]
I was able to test this with `generate_resources` being set to true, false, and not being set and got the expected behavior.
As mentioned before, I don't believe this is needed for the openshift-provision Eunomia template processor anymore, but the feature works on this branch if you want to accept it.

**Pull request closed without merging**
